import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
const $=id=>document.getElementById(id), coarse=matchMedia('(pointer:coarse)').matches||'ontouchstart'in window;
const root=$('game'),start=$('startScreen'),end=$('endScreen'),hud=$('hud'),mobile=$('mobile'),bars=$('bars'),caption=$('caption'),rift=$('riftMessage'),status=$('assetStatus');
const C={c:0x72ecff,r:0xff5b4d,o:0xffaa62,v:0xae7dff}; let scene,camera,renderer,composer,clock,player,visual,portal,carrier,modelTpl=null,mixer=null,actions={};
let started=false,ended=false,intro=-1,yaw=0,pitch=-.12,hp=100,en=100,kills=0,flight=false,dashCD=0,blastCD=0,meleeCD=0,target=null,time=0,shake=0;const keys=new Set(),input={x:0,y:0},enemies=[],shots=[],fx=[];
const mat=(c,m=.65,r=.35,e=0,i=0)=>new THREE.MeshStandardMaterial({color:c,metalness:m,roughness:r,emissive:e,emissiveIntensity:i}), glow=(c,i=4)=>mat(c,.2,.2,c,i);
function box(p,s,pos,ma){let o=new THREE.Mesh(new THREE.BoxGeometry(...s),ma);o.position.set(...pos);o.castShadow=!coarse;o.receiveShadow=true;p.add(o);return o}function cyl(p,r,pos,ma){let o=new THREE.Mesh(new THREE.CylinderGeometry(r[0],r[1],r[2],r[3]||12),ma);o.position.set(...pos);o.castShadow=!coarse;p.add(o);return o}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x04070d);scene.fog=new THREE.FogExp2(0x09111c,coarse?.014:.01);camera=new THREE.PerspectiveCamera(coarse?68:62,innerWidth/innerHeight,.1,500);renderer=new THREE.WebGLRenderer({antialias:!coarse,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.15:1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=!coarse;root.append(renderer.domElement);composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),coarse?.45:.7,.55,.83));clock=new THREE.Clock();lights();ground();city();makePortal();makeCarrier();makePlayer();rain();bind();loadModel();animate()}
function lights(){scene.add(new THREE.HemisphereLight(0x9bbce0,0x070b10,1.3));let d=new THREE.DirectionalLight(0xd9e9ff,3.5);d.position.set(-30,60,25);d.castShadow=!coarse;scene.add(d);let p=new THREE.PointLight(C.v,70,170,2);p.position.set(0,44,-92);scene.add(p)}
function ground(){let g=new THREE.Mesh(new THREE.PlaneGeometry(260,260),mat(0x090e15,.35,.45));g.rotation.x=-Math.PI/2;g.receiveShadow=true;scene.add(g);let wet=new THREE.MeshPhysicalMaterial({color:0x090d13,roughness:.18,metalness:.5,clearcoat:1});for(const [w,h]of[[30,240],[240,30]]){let r=new THREE.Mesh(new THREE.PlaneGeometry(w,h),wet);r.rotation.x=-Math.PI/2;r.position.y=.015;scene.add(r)}for(let i=0;i<20;i++){let p=new THREE.Mesh(new THREE.CircleGeometry(1+Math.random()*3,18),new THREE.MeshPhysicalMaterial({color:0x10213a,transparent:true,opacity:.23,roughness:.04,metalness:.7,clearcoat:1}));p.rotation.x=-Math.PI/2;p.scale.y=.25;p.position.set((Math.random()-.5)*70,.03,(Math.random()-.5)*80);scene.add(p)}}
function tex(){let c=document.createElement('canvas');c.width=128;c.height=256;let x=c.getContext('2d');x.fillStyle='#151e29';x.fillRect(0,0,128,256);for(let y=8;y<250;y+=14)for(let xx=7;xx<124;xx+=14){x.globalAlpha=Math.random()>.72?.6:.1;x.fillStyle=Math.random()>.72?'#d8efff':'#425266';x.fillRect(xx,y,8,6)}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function city(){let t=tex(),blocks=[-90,-62,-42,42,62,90];for(const x0 of blocks)for(const z0 of blocks){if(Math.abs(x0)<48&&Math.abs(z0)<48)continue;for(let j=0;j<2+Math.random()*2;j++){let w=12+Math.random()*13,d=12+Math.random()*13,h=25+Math.random()*70,x=x0+(Math.random()-.5)*16,z=z0+(Math.random()-.5)*16,m=new THREE.MeshStandardMaterial({map:t,color:0x51606e,roughness:.55,metalness:.25,emissive:0x0d151f,emissiveIntensity:.45});box(scene,[w,h,d],[x,h/2,z],m)}}for(let i=-3;i<=3;i++){let z=i*18;if(Math.abs(z)<7)continue;lamp(-18,z);lamp(18,z)}for(let i=0;i<9;i++)car((Math.random()-.5)*56,(Math.random()-.5)*68,Math.random()*Math.PI,i<3)}
function lamp(x,z){let g=new THREE.Group();cyl(g,[.07,.09,6,8],[0,3,0],mat(0x46525e,.8,.3));box(g,[1.5,.12,.12],[.65,5.8,0],mat(0x46525e,.8,.3));box(g,[.5,.1,.22],[1.35,5.7,0],glow(0xc7f5ff,3));g.position.set(x,0,z);scene.add(g)}
function car(x,z,r,burn){let g=new THREE.Group();box(g,[3.9,.72,1.8],[0,.7,0],mat(0x303b47,.75,.34));box(g,[1.9,.72,1.65],[.2,1.3,0],mat(0x080c11,.45,.5));if(burn){let l=new THREE.PointLight(C.o,8,18,2);l.position.y=2;g.add(l);for(let i=0;i<3;i++){let f=new THREE.Mesh(new THREE.ConeGeometry(.18,1.3,7),new THREE.MeshBasicMaterial({color:i%2?0xff5d2f:0xffb04f,transparent:true,opacity:.7}));f.position.set((Math.random()-.5),2+Math.random(),0);f.userData.flame=1;g.add(f)}}g.position.set(x,0,z);g.rotation.y=r;scene.add(g)}
function makePortal(){portal=new THREE.Group();portal.position.set(0,43,-94);for(let i=0;i<5;i++){let t=new THREE.Mesh(new THREE.TorusGeometry(16+i*2.4,.2,8,96),new THREE.MeshBasicMaterial({color:i%2?0xc08aff:0x7e5cff,transparent:true,opacity:.4-i*.04,blending:THREE.AdditiveBlending,depthWrite:false}));t.rotation.z=i*.5;t.userData.s=(i%2?1:-1)*(.08+i*.02);portal.add(t)}portal.add(new THREE.Mesh(new THREE.CircleGeometry(15,70),new THREE.MeshBasicMaterial({color:0x5f3797,transparent:true,opacity:.15,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false})));scene.add(portal)}
function makeCarrier(){carrier=new THREE.Group();let h=mat(0x121821,.88,.22),p=mat(0x303944,.8,.25),r=glow(C.r,5);let c=new THREE.Mesh(new THREE.CylinderGeometry(5,7,22,10),h);c.rotation.z=Math.PI/2;carrier.add(c);for(const s of[-1,1]){box(carrier,[22,.7,5],[0,s*3.4,0],p);box(carrier,[13,.1,.25],[1,s*3.8,2.7],r)}carrier.position.set(0,47,-126);carrier.scale.setScalar(.01);carrier.visible=false;scene.add(carrier)}
function fallback(enemy=false){let g=new THREE.Group(),d=mat(enemy?0x180d10:0x0d151e,.9,.22),s=mat(enemy?0x643230:0x354653,.87,.22),q=glow(enemy?C.r:C.c,5);let t=new THREE.Mesh(new THREE.CapsuleGeometry(.58,1.25,6,10),s);t.position.y=2.55;g.add(t);let h=new THREE.Mesh(new THREE.SphereGeometry(.42,16,12),d);h.position.y=3.9;g.add(h);box(g,[.58,.08,.05],[0,4,.4],q);for(const z of[-1,1]){let a=new THREE.Mesh(new THREE.CapsuleGeometry(.17,.9,5,8),d);a.position.set(z*.75,2.55,0);g.add(a);let l=new THREE.Mesh(new THREE.CapsuleGeometry(.22,1.2,5,8),s);l.position.set(z*.3,1,0);g.add(l)}return g}
function makePlayer(){player=new THREE.Group();visual=fallback(false);player.add(visual);player.position.set(0,0,20);player.userData.v=new THREE.Vector3();scene.add(player)}
function loadModel(){new GLTFLoader().load('https://cdn.jsdelivr.net/gh/mrdoob/three.js@dev/examples/models/gltf/Soldier.glb',g=>{modelTpl=g.scene;let m=g.scene.clone();m.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.metalness=.65;o.material.roughness=.3;o.castShadow=!coarse}});m.scale.setScalar(2.05);m.rotation.y=Math.PI;player.remove(visual);visual=m;player.add(m);mixer=new THREE.AnimationMixer(m);let clip=n=>g.animations.find(a=>a.name.toLowerCase().includes(n));actions.idle=mixer.clipAction(clip('idle')||g.animations[0]);actions.run=mixer.clipAction(clip('run')||g.animations[1]);actions.idle.play();actions.run.play();actions.run.setEffectiveWeight(0);status.classList.add('ready');status.querySelector('span').textContent='Combat suit ready'},null,()=>{status.classList.add('fallback');status.querySelector('span').textContent='Optimized fallback suit ready'})}
function enemy(i){let e=new THREE.Group();e.userData={hp:100,shoot:1+Math.random(),dead:false};e.add(modelTpl?modelTpl.clone():fallback(true));if(modelTpl){let m=e.children[0];m.scale.setScalar(1.9);m.rotation.y=Math.PI;m.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.color?.multiply(new THREE.Color(0x793a3a));o.castShadow=!coarse}})}let a=i/6*Math.PI*2+.4,r=27+Math.random()*10;e.position.set(Math.sin(a)*r,0,Math.cos(a)*r-5);scene.add(e);enemies.push(e);spawnFx(e.position)}
function rain(){let n=coarse?700:1400,p=new Float32Array(n*3);for(let i=0;i<n;i++){p[i*3]=(Math.random()-.5)*150;p[i*3+1]=Math.random()*75;p[i*3+2]=(Math.random()-.5)*150}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));let r=new THREE.Points(g,new THREE.PointsMaterial({color:0xb4d7ed,size:.05,transparent:true,opacity:.4,depthWrite:false}));r.name='rain';scene.add(r)}
function bind(){addEventListener('keydown',e=>{keys.add(e.code);if(e.code.includes('Shift'))dash();if(e.code==='KeyE')blast();if(e.code==='KeyF')fly()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0021;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0015,-.48,.42)}});renderer.domElement.addEventListener('click',()=>{if(!started)return;if(!coarse&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock?.();else melee()});if(!coarse)return;let mz=$('moveZone'),st=$('stick'),id=null,cx=0,cy=0;mz.onpointerdown=e=>{id=e.pointerId;cx=e.clientX;cy=e.clientY;st.style.display='block';st.style.left=cx+'px';st.style.top=cy+'px'};mz.onpointermove=e=>{if(e.pointerId!==id)return;let x=e.clientX-cx,y=e.clientY-cy,L=Math.hypot(x,y)||1,M=43;if(L>M){x*=M/L;y*=M/L}input.x=x/M;input.y=-y/M;st.firstElementChild.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`};let me=e=>{if(e.pointerId!==id)return;id=null;input.x=input.y=0;st.style.display='none'};mz.onpointerup=mz.onpointercancel=me;let lz=$('lookZone'),lid=null,lx=0,ly=0;lz.onpointerdown=e=>{lid=e.pointerId;lx=e.clientX;ly=e.clientY};lz.onpointermove=e=>{if(e.pointerId!==lid)return;let x=e.clientX-lx,y=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=x*.006;pitch=THREE.MathUtils.clamp(pitch-y*.0044,-.5,.42)};lz.onpointerup=lz.onpointercancel=e=>{if(e.pointerId===lid)lid=null};$('meleeBtn').onpointerdown=melee;$('blastBtn').onpointerdown=blast;$('dashBtn').onpointerdown=dash;$('flyBtn').onpointerdown=fly}
function reset(){enemies.splice(0).forEach(e=>scene.remove(e));shots.splice(0).forEach(e=>scene.remove(e));fx.splice(0).forEach(e=>scene.remove(e));hp=en=100;kills=0;flight=false;carrier.visible=false;carrier.scale.setScalar(.01);player.position.set(0,0,20);$('flyBtn').classList.remove('active');$('enemyCount').querySelector('b').textContent='0 / 6'}
function begin(){reset();started=true;ended=false;start.classList.remove('active');end.classList.remove('active');hud.classList.remove('hidden');if(coarse)mobile.classList.remove('hidden');bars.classList.add('on');caption.classList.remove('hidden');intro=0;player.position.set(0,13,21);setTimeout(()=>caption.classList.add('hidden'),2200)}
function updateIntro(dt){intro+=dt;if(intro<1.05)player.position.y=THREE.MathUtils.lerp(13,0,1-Math.pow(1-Math.min(1,intro/1.05),3));else if(intro<1.22){player.position.y=0;if(!player.userData.l){player.userData.l=1;wave(player.position,C.c,1);shake=1}}else if(intro>2.4){intro=-1;player.userData.l=0;bars.classList.remove('on');warn('SOVEREIGN SQUAD INBOUND');for(let i=0;i<6;i++)setTimeout(()=>enemy(i),i*160)}}
function move(dt){let x=input.x,y=input.y;if(keys.has('KeyW'))y++;if(keys.has('KeyS'))y--;if(keys.has('KeyD'))x++;if(keys.has('KeyA'))x--;let L=Math.hypot(x,y);if(L>1){x/=L;y/=L}let f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw)),d=new THREE.Vector3().addScaledVector(f,y).addScaledVector(r,x);if(flight&&L)d.y=-Math.sin(pitch)*.65;d.normalize();let speed=flight?15:9.5;player.userData.v.lerp(d.multiplyScalar(L?speed:0),1-Math.pow(.002,dt));player.position.addScaledVector(player.userData.v,dt);if(flight){if(!L)player.position.y+=(6.5-player.position.y)*dt*1.8;player.position.y=THREE.MathUtils.clamp(player.position.y,2.2,30)}else player.position.y*=Math.pow(.001,dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-40,40);player.position.z=THREE.MathUtils.clamp(player.position.z,-38,42);player.rotation.y=yaw;if(mixer){mixer.update(dt);actions.run.setEffectiveWeight(THREE.MathUtils.lerp(actions.run.getEffectiveWeight(),L&&!flight?1:0,.15));actions.idle.setEffectiveWeight(1-actions.run.getEffectiveWeight())}en=Math.min(100,en+dt*(flight?5:10));cam(dt);lock()}
function cam(dt){let f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw)),p=player.position.clone().addScaledVector(f,flight?-9:-7).addScaledVector(r,coarse?1.1:1.6).add(new THREE.Vector3(0,flight?5.2:4.1,0));camera.position.lerp(p,1-Math.pow(.001,dt));if(shake>.01){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake*=Math.pow(.02,dt)}camera.lookAt(player.position.clone().addScaledVector(f,14).add(new THREE.Vector3(0,2.4+pitch*10,0)))}
function lock(){let best=null,bd=999,dir=new THREE.Vector3();camera.getWorldDirection(dir);for(let e of enemies){if(e.userData.dead)continue;let p=e.position.clone().add(new THREE.Vector3(0,2,0)),to=p.sub(camera.position),dist=to.length();to.normalize();let a=Math.acos(THREE.MathUtils.clamp(dir.dot(to),-1,1)),s=a+dist/150;if(a<(coarse?.55:.35)&&s<bd){bd=s;best=e}}target=best;let ui=$('targetLock');if(best){let p=best.position.clone().add(new THREE.Vector3(0,2,0)).project(camera),x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;ui.classList.remove('hidden');ui.style.left=x+'px';ui.style.top=y+'px';$('targetText').textContent=Math.round(best.position.distanceTo(player.position))+'M'}else ui.classList.add('hidden')}
function melee(){if(!started||ended||intro>=0||meleeCD>0)return;meleeCD=.45;let e=target&&target.position.distanceTo(player.position)<5.5?target:near(5.5);if(e){hitEnemy(e,48);wave(e.position,C.c,.45)}else impact(player.position.clone().add(new THREE.Vector3(Math.sin(yaw)*2,1.4,-Math.cos(yaw)*2)),C.c)}
function blast(){if(!started||ended||intro>=0||blastCD>0||en<11)return;blastCD=.32;en-=11;let e=target||near(34),a=player.position.clone().add(new THREE.Vector3(.5,2.1,.2)),b=e?e.position.clone().add(new THREE.Vector3(0,2,0)):a.clone().add(new THREE.Vector3(Math.sin(yaw)*50,0,-Math.cos(yaw)*50));beam(a,b,C.c,.065);if(e){hitEnemy(e,27);impact(b,C.c)}}
function dash(){if(!started||ended||intro>=0||dashCD>0||en<16)return;dashCD=2.7;en-=16;let d=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw));player.position.addScaledVector(d,flight?10:7);wave(player.position,C.c,.7);shake=.25}
function fly(){if(!started||ended||intro>=0)return;flight=!flight;$('flyBtn').classList.toggle('active',flight);if(flight)player.position.y=Math.max(2.5,player.position.y);warn(flight?'VECTOR FLIGHT // ONLINE':'GROUND MODE // RESTORED')}
function near(max){let b=null,d=max;for(let e of enemies){let q=e.position.distanceTo(player.position);if(!e.userData.dead&&q<d){d=q;b=e}}return b}function hitEnemy(e,d){e.userData.hp-=d;if(e.userData.hp<=0&&!e.userData.dead){e.userData.dead=true;kills++;$('enemyCount').querySelector('b').textContent=`${kills} / 6`;boom(e.position.clone().add(new THREE.Vector3(0,1.5,0)));setTimeout(()=>{scene.remove(e);let i=enemies.indexOf(e);if(i>=0)enemies.splice(i,1)},80);if(kills===6)setTimeout(riftEvent,500)}}
function ai(dt){for(let e of enemies){if(e.userData.dead)continue;e.userData.shoot-=dt;let to=player.position.clone().setY(0).sub(e.position),d=to.length();if(d>7)e.position.addScaledVector(to.normalize(),dt*4);e.lookAt(player.position.x,0,player.position.z);if(e.userData.shoot<=0&&d<34){let p=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),new THREE.MeshBasicMaterial({color:C.r}));p.position.copy(e.position).add(new THREE.Vector3(0,2,0));p.userData={v:player.position.clone().add(new THREE.Vector3(0,1.7,0)).sub(p.position).normalize().multiplyScalar(20),life:2.5};scene.add(p);shots.push(p);e.userData.shoot=1.3+Math.random()*.8}}}
function shotUpdate(dt){for(let i=shots.length-1;i>=0;i--){let p=shots[i];p.position.addScaledVector(p.userData.v,dt);p.userData.life-=dt;if(p.position.distanceTo(player.position.clone().add(new THREE.Vector3(0,1.6,0)))<1){hp=Math.max(0,hp-8);$('hitFlash').classList.remove('on');void $('hitFlash').offsetWidth;$('hitFlash').classList.add('on');shake=.35;scene.remove(p);shots.splice(i,1)}else if(p.userData.life<=0){scene.remove(p);shots.splice(i,1)}}}
function riftEvent(){bars.classList.add('on');rift.classList.remove('hidden');carrier.visible=true;warn('MASSIVE TRANSIT SIGNATURE');shake=1.3;setTimeout(()=>{rift.classList.add('hidden');bars.classList.remove('on')},2200);setTimeout(win,5000)}function win(){ended=true;mobile.classList.add('hidden');bars.classList.add('on');setTimeout(()=>end.classList.add('active'),800)}
function beam(a,b,c,w=.05){let d=b.clone().sub(a),l=d.length(),o=new THREE.Mesh(new THREE.CylinderGeometry(w,w,l,6),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.95,blending:THREE.AdditiveBlending,depthWrite:false}));o.position.copy(a.clone().add(b).multiplyScalar(.5));o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());o.userData={life:.1,max:.1};scene.add(o);fx.push(o)}
function impact(p,c){for(let i=0;i<6;i++){let s=new THREE.Mesh(new THREE.SphereGeometry(.04,5,4),new THREE.MeshBasicMaterial({color:c,transparent:true}));s.position.copy(p);s.userData={life:.35,max:.35,v:new THREE.Vector3((Math.random()-.5)*6,Math.random()*5,(Math.random()-.5)*6)};scene.add(s);fx.push(s)}}function boom(p){impact(p,C.o);let s=new THREE.Mesh(new THREE.SphereGeometry(.5,10,8),new THREE.MeshBasicMaterial({color:C.o,transparent:true,opacity:.55,blending:THREE.AdditiveBlending}));s.position.copy(p);s.userData={life:.4,max:.4,g:6};scene.add(s);fx.push(s);shake=.45}function wave(p,c,k=1){let r=new THREE.Mesh(new THREE.RingGeometry(.55,.75,36),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.7,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));r.rotation.x=-Math.PI/2;r.position.copy(p);r.position.y=.07;r.scale.setScalar(k);r.userData={life:.5,max:.5,g:12};scene.add(r);fx.push(r)}function spawnFx(p){wave(p,C.v,.6)}
function fxUpdate(dt){for(let i=fx.length-1;i>=0;i--){let o=fx[i];o.userData.life-=dt;if(o.material)o.material.opacity=Math.max(0,o.userData.life/o.userData.max);if(o.userData.v)o.position.addScaledVector(o.userData.v,dt);if(o.userData.g)o.scale.addScalar(o.userData.g*dt);if(o.userData.life<=0){scene.remove(o);fx.splice(i,1)}}}
function world(dt){portal.children.forEach(o=>o.userData.s&&(o.rotation.z+=o.userData.s*dt));portal.scale.setScalar(1+Math.sin(time)*.025+(carrier.visible?.45:0));if(carrier.visible){carrier.scale.lerp(new THREE.Vector3(1,1,1),.05);carrier.position.z=Math.min(-84,carrier.position.z+dt*5)}scene.traverse(o=>{if(o.userData.flame){o.scale.y=.6+Math.random();o.material.opacity=.4+Math.random()*.4}});let r=scene.getObjectByName('rain');if(r){let a=r.geometry.attributes.position;for(let i=0;i<a.count;i++){a.array[i*3+1]-=dt*32;if(a.array[i*3+1]<0)a.array[i*3+1]=75}a.needsUpdate=true}}
function ui(dt){dashCD=Math.max(0,dashCD-dt);blastCD=Math.max(0,blastCD-dt);meleeCD=Math.max(0,meleeCD-dt);$('hpText').textContent=Math.ceil(hp);$('hpFill').style.width=hp+'%';$('energyText').textContent=Math.ceil(en);$('energyFill').style.width=en+'%'}function warn(t){let w=$('warning');w.textContent=t;w.classList.add('show');clearTimeout(w.t);w.t=setTimeout(()=>w.classList.remove('show'),900)}
function animate(){requestAnimationFrame(animate);let dt=Math.min(.033,clock.getDelta());time+=dt;world(dt);if(started&&!ended){if(intro>=0)updateIntro(dt);else{move(dt);ai(dt);shotUpdate(dt);ui(dt)}fxUpdate(dt)}else{camera.position.lerp(new THREE.Vector3(9,7,26),.02);camera.lookAt(0,2.5,13)}composer.render()}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});$('startBtn').onclick=begin;$('restartBtn').onclick=begin;init();
